image:
  registry: ghcr.io
  repository: canozokur
  name: mysql-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecrets:
    enabled: false
    secretName:

envs:
    imagesPullPolicy: IfNotPresent
    imagesDefaultRegistry: 
    imagesDefaultRepository:
