name: Build mysql-operator container image
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up docker context for buildx
        run: |
          docker context create operator-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate mysql-operator dockerfile
        run: |
          bash gen_dockerfile.sh "" ghcr.io/canozokur/mysql-operator-python-deps

      - name: Generate image tag
        run: |
          bash tag.sh | awk '{print "IMG_TAG="$1}' >> $GITHUB_OUTPUT
        id: img_tag

      - name: Set up docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/canozokur/mysql-operator
          tags: |
            type=raw,value=${{ steps.img_tag.outputs.IMG_TAG }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: operator-build

      - name: Build mysql-operator
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
