name: Build mysql-operator-python-deps container image
on:
  workflow_dispatch:
  push:
    branches: ['canozokur/arm64-build']
    paths: ['docker-deps/*']
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker context for buildx
        run: |
          docker context create buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/canozokur/mysql-operator-python-deps
          tags: |
            type=raw,value=3.9.5
          labels: |
            org.opencontainers.image.title=mysql-operator-python-deps
            org.opencontainers.image.description=MySQL Operator for Kubernetes build dependency container image

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: buildx

      - name: Build python deps container
        uses: docker/build-push-action@v3
        with:
          context: docker-deps/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
